# Generated by Django 6.0a1 on 2025-10-10 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_category_question"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="correct_answer",
            field=models.CharField(default="not provided", max_length=500),
            preserve_default=False,
        ),
    ]
