# Generated by Django 6.0a1 on 2025-10-11 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_question_correct_answer"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="correct_answer_ru",
            field=models.TextField(blank=True, null=True),
        ),
    ]
