repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/psf/black
    rev: 25.9.0
    hooks:
      - id: black
        files: ^backend/

  - repo: https://github.com/pycqa/isort
    rev: 7.0.0
    hooks:
      - id: isort
        name: isort (python)
        files: ^backend/

  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        files: ^backend/

  - repo: https://github.com/pycqa/bandit
    rev: 1.8.6
    hooks:
      - id: bandit
        files: ^backend/
        exclude: ^backend/api/tests\.py

  - repo: https://github.com/hadolint/hadolint
    rev: v2.14.0
    hooks:
      - id: hadolint-docker
        files: ^.*Dockerfile$

  - repo: local
    hooks:
      - id: frontend-lint
        name: frontend-lint
        entry: cd frontend && npm run lint
        language: node
        files: ^frontend/(js|jsx|ts|tsx)$
        pass_filenames: false

      - id: frontend-format
        name: frontend-format
        entry: cd frontend && npm run lint:fix && npm run format
        language: node
        files: ^frontend/(js|jsx|ts|tsx|json|css|md)$
        pass_filenames: false
